Update lcp cli

diff --git a/scripts/lcp b/scripts/lcp
--- a/scripts/lcp
+++ b/scripts/lcp
@@ -50,7 +50,7 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         -h|--help)
-            echo "Usage: lcp [OPTION]... [lxhost]:SRC [SRC]... DEST"
+            echo "Usage: lcp [OPTION]... [lxhost]:SRC [:SRC]... DEST"
             echo "   or  lcp [OPTION]... SRC [SRC]... [lxhost]:DEST"
             echo
             echo "LXPlus rsync wrapper."
@@ -74,7 +74,7 @@ while [[ $# -gt 0 ]]; do
             echo
             echo "Examples:"
             echo "  lcp :a/b/c.txt .                → rsync -ach --partial --info=progress2 \$CERN_USERNAME@lxplus.cern.ch:a/b/c.txt ."
-            echo "  lcp :a/b/c.txt a/b/d.txt .      → rsync -ach --partial --info=progress2 \$CERN_USERNAME@lxplus.cern.ch:a/b/{c,d}.txt ."
+            echo "  lcp :a/b/c.txt :a/b/d.txt .     → rsync -ach --partial --info=progress2 \$CERN_USERNAME@lxplus.cern.ch:a/b/{c,d}.txt ."
             echo "  lcp test_dir abm9:/tmp/test     → rsync -ach --partial --info=progress2 test_dir \$CERN_USERNAME@lxplus8s09.cern.ch:/tmp/test"
             exit 0
             ;;
@@ -87,88 +87,66 @@ while [[ $# -gt 0 ]]; do
             exit 1
             ;;
         *)
+            # First argument (must be a source)
             if [[ "$began_parsing_destsrc" = false ]]; then
-                # First argument (must be a source!)
+                began_parsing_destsrc=true
                 
-                # Case: host:[src] ... dest
-                if [[ "$1" =~ ^([^:/]*):(.*)$ ]]; then
+                # Case: host:src ... dest
+                # (remote source)
+                if [[ "$1" =~ ^([^:/]*):(.+)$ ]]; then
                     is_src_remote=true
                     lxhost_arg="${BASH_REMATCH[1]}"
-
-                    # Check if there is a source after the ':'
-                    if [[ -n "${BASH_REMATCH[2]}" ]]; then
-                        sources+=("${BASH_REMATCH[2]}")
-                    fi
-
-                    shift
-
-                # Case: host :src ... dest
-                elif [[ $# -gt 2 && "$2" =~ ^:(.+)$ ]]; then
-                    is_src_remote=true
-                    lxhost_arg="$1"
-                    sources+=("${BASH_REMATCH[1]}")
-
-                    shift 2
-
-                # Case: host : src ... dest
-                elif [[ $# -gt 3 && "$2" = ":" ]]; then
-                    is_src_remote=true
-                    lxhost_arg="$1"
-
-                    shift 2 # Leave the src for later parsing
-
-                # Case: src ... (host:dest | host :dest | host : dest)
-                else
-                    sources+=("$1")
-                    shift
-                fi
-
-                began_parsing_destsrc=true
-
-            else
-                # Subsequent arguments (could be sources or destination)
+                    sources+=("${BASH_REMATCH[2]}")
 
                 # Case: src ... host:dest
-                if [[ $# -eq 1 && "$1" =~ ^([^:/]*):(.+)$ ]]; then
+                # (local source)
+                else
+                    sources+=("$1")
+                fi
+
+            # Last argument (must be the destination)
+            elif [[ $# -eq 1 ]]; then
+
+                # Case: src ... host:dest
+                # (remote destination)
+                if [[ "$1" =~ ^([^:/]*):(.+)$ ]]; then
                     is_dest_remote=true
                     lxhost_arg="${BASH_REMATCH[1]}"
                     dest="${BASH_REMATCH[2]}"
 
-                    shift
-
-                # Case: src ... host: dest
-                elif [[ $# -eq 2 && "$1" =~ ^([^:/]+):$ ]]; then
-                    is_dest_remote=true
-                    lxhost_arg="${BASH_REMATCH[1]}"
-                    dest="$2"
-
-                    shift 2
-
                 # Case: host:src ... dest
-                elif [[ $# -eq 1 ]]; then
-                    # Check that the argument either doesn't have a ':', or it has a ':' only after a first '/'
-                    # (but not necessarily immediately after it)
-                    if [[ "$1" =~ ^([^:]+|[^:/]/.*)$ ]]; then
-                        dest="$1"
-                        shift
-                    else
-                        echo "lcp: missing path for remote destination" >&2
-                        exit 1
-                    fi
-
-                # Other sources
+                # (local destination)
                 else
-                    # Check that the argument either doesn't have a ':', or it has a ':' only after a first '/'
-                    # (but not necessarily immediately after it)
-                    if [[ "$1" =~ ^([^:]+|[^:/]/.*)$ ]]; then
-                        sources+=("$1")
-                        shift
-                    else
-                        echo "lcp: cannot have sources from multiple remote hosts" >&2
-                        exit 1
-                    fi
+                    dest="$1"
+                fi
+
+            # Middle argument: additional remote source
+            # Case: ... [host]:src ...
+            elif [[ "$1" =~ ^([^:/]*):(.+)$ ]]; then
+                if [[ "$is_src_remote" = false ]]; then
+                    echo "lcp: Cannot mix local and remote sources" >&2
+                    exit 1
+                elif [[ -n "${BASH_REMATCH[1]}" ]] && [[ "${BASH_REMATCH[1]}" != "${lxhost_arg}" ]]; then
+                    echo "lcp: Cannot have sources from multiple remote hosts" >&2
+                    exit 1
+                else
+                    # Either we didn't provide a remote host (use the one from the first source),
+                    # or we explicitly provided the same one
+                    sources+=("${BASH_REMATCH[2]}")
+                fi
+
+            # Middle argument: additional local source
+            # Case: ... src ...
+            else
+                if [[ "$is_src_remote" = true ]]; then
+                    echo "Cannot mix local and remote sources" >&2
+                    exit 1
+                else
+                    sources+=("$1")
                 fi
             fi
+
+            shift
             ;;
     esac
 done
